export * from './auth.model';
export * from './recievednews.model';
export * from './user.model';
export * from './mark.model';
export * from './subject.model';
export * from './sentmessage.model';
export * from './recievedmessage.model';
export * from './group.model';
export * from './sentnews.model';
